### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by jhsu802701** [MX-Linux/build-iso-mx#2]
I'd like to Dockerize this project.  Building this app in a Docker container (instead of on the host OS) provides a uniform experience for everyone.

**Comment by rharmonson** [comment]
and hated by those who don't use nor want to use Docker. Not Trolling, but too many projects and developers are moving to Docker then fail to provide alternatives. Besides if not Docker, why not LXC or a virtual appliance or .. something else.

Feel me? and I am necro-bumping? Apologies.

**Comment by AdrianTM** [comment]
Not interested at this moment to use Docker
