### ISSUE TITLE
Missing modules in initrd

### ISSUE THREAD

**Issue by timkenhan** [MX-Linux/build-iso-mx#20]
After building, initrd seems to be missing `/lib/modules`, which causes this error:

    Neither aufs nor overlayfs is available

This was tried with `defaults-kde` with mxkde template

![Screenshot_20220718_202428](https://user-images.githubusercontent.com/33104842/179526880-307d0e88-e29c-4304-99c5-e866f074110a.png)
.

**Comment by AdrianTM** [comment]
Works fine here. Check the log errors in Output/build-iso.log

**Comment by timkenhan** [comment]
This appears:

    xargs: modprobe: No such file or directory
    cp: cannot stat '': No such file or directory

This originates from the copy-initrd-modules script.

How are you running it exactly? Might worth documenting...

**Comment by AdrianTM** [comment]
I don't do anything special, just run it with `./build-iso --user-default defaults-kde` it works in MX and even in Debian installed in WSL.

How are you running it? On what kind of system?

That xargs modprobe command is present in Tools/module-depends and Tools/copy-initrd-modules, maybe if you look into those or if you add some printouts might give you an idea what is going on.

**Comment by timkenhan** [comment]
I am running it on a regular Debian 11.

I just tried again, adding sudo in front of the modprobe command seems to do the trick!

It appears the root of the issue is that the user I am on does not have /sbin or /usr/sbin on its PATH. Mind you that this is a common practice.

What would you suggest? Adding /sbin and /usr/sbin to the PATH for regular users seem to be an antipatern for a lot of people...

**Comment by timkenhan** [comment]
Having the full path (e.g. /sbin/modprobe) seems to also work (without sudo)

**Comment by AdrianTM** [comment]
> It appears the root of the issue is that the user I am on does not have /sbin or /usr/sbin on its PATH. Mind you that this is a common practice.

It works fine in MX, we don't necessarily test on other distros. Not sure what's the best solution, maybe add /sbin and /usr/sbin to the PATH inside the script to make sure people who don't have that can run programs from /sbin and /usr/sbin.  I would not necessarily like to add the full path for all the commands used inside the script. In case of modeprobe it might make sense to use sudo,
