### ISSUE TITLE
no_check_errors variable is never set

### ISSUE THREAD

**Issue by jhsu802701** [MX-Linux/build-iso-mx#40]
The no_check_errors variable has only two instances in the entire build-iso script:
*  The variable no_check_errors is defined near the beginning of main().
*  This variable is used in the definitions of _check_errors_ (if [[ -n $no_check_errors ]]; then).

However, the no_check_errors variable is never set to any value.  Is this a future feature?

**Comment by dolphinoracle** [comment]
its a command line switch that sets the "disable_errors" variable used in the rest of the script.

 -no-error-check|n) disable_errors=true                        ;;
    -NO-ERROR-LOG|N)  no_log_errors=true ; disable_errors=true  ;;

**Comment by dolphinoracle** [comment]
Oh, I got the variable mixed up with the command line switch.

Its possible the variable is never set.

**Comment by AdrianTM** [comment]
I guess you could pass that when you invoke the script, but i don't think
we ever used that. We can safely remove that piece if code.
