### ISSUE TITLE
Missing packages 

### ISSUE THREAD

**Issue by timkenhan** [MX-Linux/build-iso-mx#55]
Got this error on stage 4 part 8:
````
E: Failed to fetch http://mxrepo.com/mx/repo/pool/main/m/mx-system-sounds/mx-system-sounds_22.11.01_amd64.deb  404  Not Found [IP: 70.40.214.183 80]
````

When I looked into the repo in question, the file `mx-system-sounds_22.11.01_amd64.deb` does not exist, yet `mx-system-sounds_22.11.02_amd64.deb` does.

With some grep command, I was able to pinpoint the file `Remaster/work/MX-21.2.1-x64-bullseye/squashfs/var/lib/apt/lists/mxrepo.com_mx_repo_dists_bullseye_main_binary-amd64_Packages` to have the package name in question.

AFAIK, this file is the pkg db from the repo itself. If this is true, it means there's a discrepancies on the MX repo itself.

**Comment by dolphinoracle** [comment]
sounds like a bad repo sync.  we updated last nite.  will let the repo manager know.
